import type { Metadata } from "next";
import "./globals.css";
import Header from "@/component/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <div className="w-full mx-auto py-5 px-2">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
